name: Publish to NPM

on:
  push: 
    branches: [ main ]
  
# release:
# types: [created]

jobs:
  publish: # JOB
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code ğŸ˜
        uses: actions/checkout@v3

      - name: Setup Node ğŸ˜
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"

      - name: Install Dependences and Build ğŸ˜±
        run: npm ci && npm run build

      - name: Keep same version (litte time) ğŸ¤— version = ${{ github.GITHUB_REF }}
        env: 
          GITHUB_TOKEN: ${{ secrets.ACCESS_TO_REPO }}
        run: npm version 1.0.0 --allow-same-version

      - name: Publish package on NPM ğŸ˜
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_NPM }}
